/*	$NetBSD$	*/
#ifndef EVBARM_GRPEACH_PLATFORM_H
#define EVBARM_GRPEACH_PLATFORM_H

#include <arm/rza1/rza1_reg.h>

#define KERNEL_VM_BASE		(KERNEL_BASE + 0x40000000)
#define KERNEL_VM_TOP		((0xfff00000 - RZA1_IO_SIZE) & -L1_SS_SIZE)
#define KERNEL_VM_SIZE		(KERNEL_VM_TOP - KERNEL_VM_SIZE)

#define KERNEL_IO_VBASE		KERNEL_VM_TOP
#define KERNEL_IO_SPI_VBASE	KERNEL_IO_VBASE
#define KERNEL_IO_IO0_VBASE	(KERNEL_IO_VBASE + RZA1_SPI_SIZE)
#define KERNEL_IO_IO1_VBASE	(KERNEL_IO_IO0_VBASE + RZA1_IO0_SIZE)
#define KERNEL_IO_IO2_VBASE	(KERNEL_IO_IO1_VBASE + RZA1_IO1_SIZE)
#define KERNEL_IO_IO3_VBASE	(KERNEL_IO_IO2_VBASE + RZA1_IO2_SIZE)
#define KERNEL_IO_IO4_VBASE	(KERNEL_IO_IO3_VBASE + RZA1_IO3_SIZE)
#define KERNEL_IO_ARMCORE_VBASE	(KERNEL_IO_IO4_VBASE + RZA1_IO4_SIZE)
#define KERNEL_IO_END_VBASE	(KERNEL_IO_ARMCORE_VBASE + RZA1_ARMCORE_SIZE)

//#define KERNEL_IO1_BASE	(0x3fefa000)
//#define KERNEL_IO1_SIZE (0x40000000 - KERNEL_IO1_BASE)
//#define KERNEL_IO2_BASE	(0xe8000000)
//#define KERNEL_IO2_SIZE (0x100000000 - KERNEL_IO2_BASE)

#endif	/* !EVBARM_GRPEACH_PLATFORM_H */
